version: "3"

services:
  db:
    image: library/postgres:10.5-alpine
    environment:
      POSTGRES_DB: main
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - 55432:5432
    volumes:
      - ./postgresql:/etc/postgresql:ro

volumes:
  data:
    driver: local
